version: '3'

services:

    php:
        build:
            context: ./bin/${PHPVERSION}
        container_name: '${COMPOSE_PROJECT_NAME}-${PHPVERSION}'
        restart: 'always'
        env_file:
            - .env
        volumes:
            - ./docker/php/php.ini:/usr/local/etc/php/php.ini
            - .:/var/www:cached

    nginx:
        build:
            context: ./bin/nginx
        container_name: '${COMPOSE_PROJECT_NAME}-nginx'
        restart: 'always'
        links:
            - mysql
            - php
        ports:
            - ${SERVER_PORT}:80
            - ${SERVER_PORT_SSL}:443
        volumes:
            - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./log:/var/log/nginx
            - ./public:/var/www/public
    
    mysql:
        build:
            context: ./bin/${DATABASE}
        container_name: '${COMPOSE_PROJECT_NAME}-mysql'
        restart: 'always'
        environment:
            - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
            - MYSQL_DATABASE=${DB_NAME}
            - MYSQL_USER=${DB_USER}
            - MYSQL_PASSWORD=${DB_PASSWORD}
        volumes:
            - ./docker/mysql/custom.cnf:/etc/mysql/conf.d/custom.cnf
            - ./log:/var/log/mysql
            - ./docker/db:/var/lib/mysql:cached

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: '${COMPOSE_PROJECT_NAME}-phpmyadmin'
        restart: 'always'
        ports:
            - ${PMA_PORT}:80
        environment:
            - PMA_HOST=${DB_HOST}

    maildev:
        image: djfarrelly/maildev
        ports:
            - ${MAIL_DEV_PORT}:80
